### Right post
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Thomas Ghali",
  "number": "12-42-4657567"
}

### Wrong post (missing info)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Thomas Ghali",
  "number": ""
}

### Wrong post (existing name)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "21-98-65465435"
}
