### Right delete
DELETE http://localhost:3001/api/persons/2

### Wrong delete
DELETE http://localhost:3001/api/persons/5

### Right post
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Thomas Ghali",
  "number": "12-42-4657567"
}

### Wrong post
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Thomas Ghali",
  "number": ""
}
